language: python

# whitelist
branches:
  only:
    - master
    - deployment

python:
  - "2.7"

install: 'pip install -r requirements.txt'

script: cd estmator_project; python manage.py test

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql
