language: python

notifications:
  email:
    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

# whitelist
branches:
  only:
    - master
    - development
    - test

python:
  - "2.7"

# Django versions to test against
env:
  - DJANGO_VERSION=1.8.3 SECRET_KEY='sooper-s3cr3+-k3y' DEBUG='True' DJANGO_SETTINGS_MODULE='estmator_project.settings'

# before_install:
#   - sudo apt-get -y update
#   - sudo apt-get -y install libzmq-dev

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - cd estmator_project
  - python manage.py test
